image: ubuntu:14.04

build:
  stage: build
  before_script:
    - sudo apt-get update
    - sudo apt-get install --yes --force-yes linux-image-extra-$(uname -r) linux-image-extra-virtual apt-transport-https ca-certificates
    - sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
    - echo "deb https://apt.dockerproject.org/repo ubuntu-trusty main" >> /etc/apt/sources.list.d/docker.list
    - sudo apt-get update
    - sudo apt-get install --yes --force-yes docker-engine

  script: 
    - docker build -t $CI_PROJECT_NAME .
